[config]

[stack.config]
id="default"
shared_stack_stub=false
shared_stack = true

[stack.noc]

[[stack.interface]]
type = "http"
listen = "127.0.0.1:1318"

[[stack.interface]]
type = "http-bdt"
vport = "84"

[[stack.interface]]
type = "ws"
enable = true
listen = "127.0.0.1:1319"

[[stack.bdt.endpoint]]
optional = true
host = "$none_local_ip_v4"
port = 8050
protocol = "tcp"

[[stack.bdt.endpoint]]
optional = true
host = "$none_local_ip_v4"
port = 8050
protocol = "udp"

[[stack.bdt.endpoint]]
optional = true
host = "$ip_v6"
port = 8050
protocol = "tcp"


[[stack.bdt.endpoint]]
optional = true
host = "$ip_v6"
port = 8050
protocol = "udp"
 
[stack.bdt.config]
device = "device"

# TCP port mapping to the WAN address, if there is one
# tcp_port_mapping = 8050

# disable udp transport but sn online via udp only, default is false
# udp_sn_only = false

# sn work mode, "none" will disable sn, default is "normal"
# sn_mode = "normal"

# sn ping interval in seconds, default is 25
# ping_interval = 25
