[package]
name = "cyfs-monitor"
version = "0.5.0"
edition = "2021"
license = "BSD-2-Clause"
description = "Rust cyfs-monitor package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cyfs-util = { path = "../../component/cyfs-util" }
cyfs-base = { path = "../../component/cyfs-base" }
cyfs-core = { path = "../../component/cyfs-core" }
cyfs-debug = { path = "../../component/cyfs-debug" }
cyfs-meta-lib = { path = "../../component/cyfs-meta-lib" }
cyfs-base-meta = { path = "../../component/cyfs-base-meta" }
cyfs-client = { path = "../../tools/cyfs-client" }
async-std = { version = "1.11", features = ["attributes", "tokio1"] }
async-trait = "0.1.53"
log = "0.4"
url = "2.2"
rand = "0.7"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
surf = { version = "2.3", default-features = false, features = [
    "h1-client-rustls",
] }
once_cell = "1.12"
clap = "2.34.0"
chrono = "0.4"
