[package]
name = "app-manager-lib"
version = "0.5.0"
edition = "2021"
license = "BSD-2-Clause"
description = "Rust app-manager-lib package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4", features = ["max_level_trace", "release_max_level_trace"] }
toml = "0.5"
cyfs-base = {path="../../component/cyfs-base"}
cyfs-core = {path="../../component/cyfs-core"}
cyfs-util = { path = "../../component/cyfs-util" }
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
cyfs-debug = { path = "../../component/cyfs-debug" }