[package]
name = "bdt-debuger-deamon"
version = "0.5.0"
authors = ["swjtusw <swjtusw@126.com>"]
edition = "2021"
license = "BSD-2-Clause"
description = "Rust bdt-debuger-deamon package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cyfs-debug = { path = "../../component/cyfs-debug" }
cyfs-base = { path = "../../component/cyfs-base" }
cyfs-bdt = { path = "../../component/cyfs-bdt" }
cyfs-util = { path = '../../component/cyfs-util', version = '0.6' }
async-std = { version = "1.11", features = ["unstable", "attributes"] }
clap = "2.34.0"
log = "0.4"
md5 = "0.7.0"