[package]
name = "sn-online-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cyfs-bdt = { path = "../../component/cyfs-bdt" }
cyfs-base = { path = "../../component/cyfs-base" }
cyfs-util = { path = "../../component/cyfs-util" }
clap = "2.34.0"
async-std = { version = "1.11", features = ["attributes"] }
log = "0.4"
simple_logger = "4"
rand = "0.7"
