[package]
name = "ood-control"
version = "0.5.1"
authors = ["liyaxing <liyaxing@buckyos.com>"]
edition = "2021"
license = "BSD-2-Clause"
description = "Rust ood-control package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cyfs-base = { path = "../../component/cyfs-base" }
cyfs-debug = { path = "../../component/cyfs-debug" }
cyfs-util = { path = "../../component/cyfs-util" }
cyfs-lib = { path = "../../component/cyfs-lib" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
async-std = { version = "1.11", features = ["unstable", "attributes"] }
async-h1 = { package = "cyfs-async-h1", version = '2.3.3' }
http-types = "2.12"
sysinfo = "0.26"
tide = "0.16"
hex = "0.4"
futures = "0.3"
once_cell = "1.12"
rand = "0.8"
lazy_static = "1.4"
async-trait = "0.1.53"

[target.'cfg(all(not(target_os = "android"), not(target_os = "ios")))'.dependencies]
mac_address = "1.1.3"

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.19"
android_logger = "0.11"

[lib]
name = "ood_control"
crate-type = ["lib", "cdylib", "staticlib"]
