use cyfs_base::*;

pub(crate) static CONTRACT_OBJECT_TYPE: u16 = OBJECT_TYPE_DECAPP_START + 1;
pub(crate) static CONTRACT_STATE_OBJECT_TYPE: u16 = OBJECT_TYPE_DECAPP_START + 2;
pub(crate) static CONTRACT_DATA_SOURCE_STUB_OBJECT_TYPE: u16 = OBJECT_TYPE_DECAPP_START + 3;

pub(crate) static CHALLENGE_OBJECT_TYPE: u16 = OBJECT_TYPE_DECAPP_START + 11;
pub(crate) static PROOF_OBJECT_TYPE: u16 = OBJECT_TYPE_DECAPP_START + 12;

pub(crate) static QUERY_OBJECT_TYPE: u16 = OBJECT_TYPE_DECAPP_START + 21;
pub(crate) static CACHE_OBJECT_TYPE: u16 = OBJECT_TYPE_DECAPP_START + 22;