[package]
name = "cyfs-perf-client"
version = "0.5.0"
authors = ["wangzhi <wangzhi@buckyos.com>"]
edition = "2021"
license = "BSD-2-Clause"
description = "Rust cyfs-perf-client package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4", features = [
    "max_level_trace",
    "release_max_level_trace",
] }
serde_json = "1.0"
int-enum = "0.4"
cyfs-perf-base = { path = "../cyfs-perf-base", version = "0.5" }
cyfs-util = { path = "../../../component/cyfs-util"}
cyfs-debug = { path = "../../../component/cyfs-debug", version = "0.5" }
cyfs-base = { path = "../../../component/cyfs-base", version = "0.5" }
cyfs-core = { path = "../../../component/cyfs-core", version = "0.5" }
cyfs-lib = { path = "../../../component/cyfs-lib", version = "0.5" }
cyfs-meta-lib = { path = "../../../component/cyfs-meta-lib", version = "0.5" }
async-std = { version = "1.11", features = ["unstable", "attributes"] }
rand = "0.8"
sha2 = "0.10"
async-trait = "0.1.53"
chrono = '0.4'

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.19"
android_logger = "0.11"

# [lib]
# name = "cyfs_perf"
# crate-type = ["cdylib", "staticlib"]
