
[package]
name = 'cyfs-perf-client'
version = '0.6.1'
authors = ['wangzhi <wangzhi@buckyos.com>']
edition = '2021'
license = 'BSD-2-Clause'
description = 'Rust cyfs-perf-client package'

[dependencies]
log = { version = '0.4', features = [
	'max_level_trace',
	'release_max_level_trace',
] }
serde_json = '1.0'
int-enum = '0.4'
cyfs-perf-base = { path = '../cyfs-perf-base', version = '0.6' }
cyfs-util = { path = '../../../component/cyfs-util', version = '0.6' }
cyfs-debug = { path = '../../../component/cyfs-debug', version = '0.6' }
cyfs-base = { path = '../../../component/cyfs-base', version = '0.6' }
cyfs-core = { path = '../../../component/cyfs-core', version = '0.6' }
cyfs-lib = { path = '../../../component/cyfs-lib', version = '0.8' }
cyfs-meta-lib = { path = '../../../component/cyfs-meta-lib', version = '0.6' }
async-std = { version = '1.11', features = ['unstable', 'attributes'] }
rand = '0.7'
sha2 = '0.8'
async-trait = '0.1.53'

[target.'cfg(target_os = "android")'.dependencies]
jni = '0.19'
android_logger = '0.11'
