[package]
name = "perf-service"
version = "0.5.0"
authors = ["wangzhi <wangzhi@buckyos.com>"]
edition = "2021"
license = "BSD-2-Clause"
description = "Rust perf-service package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["mongo"]
mongo = ["mongodb", "bson"]

[dependencies]
cyfs-perf-base = { path = "../../component/cyfs-perf/cyfs-perf-base" }
cyfs-base = { path = "../../component/cyfs-base" }
cyfs-debug = { path = "../../component/cyfs-debug" }
cyfs-core = { path = "../../component/cyfs-core" }
cyfs-util = { path = "../../component/cyfs-util" }
async-std = { version = "1.11", features = ["unstable", "attributes"] }
cyfs-lib = { path = "../../component/cyfs-lib" }
log = "0.4"
async-trait = "0.1.53"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mongodb = { version = "1.1.1", default-features = false, features = [
    "async-std-runtime",
], optional = true }
bson = { version = "1.1", optional = true }
lru_time_cache = { version = "0.11", optional = true }
toml = "0.5"
