[package]
name = "misc-util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
mail = ["dep:lettre"]

[dependencies]
cyfs-base = { path = "../../component/cyfs-base" }
lettre = { version = "0.10", optional = true }
serde = { version = "1.0" }
log = "0.4"
