[package]
name = "evm-gasometer"
version = "0.26.0"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>", "Parity Technologies <admin@parity.io>"]
description = "Portable Ethereum Virtual Machine implementation written in pure Rust."
repository = "https://github.com/sorpaas/rust-evm"
keywords = ["no_std", "ethereum"]
edition = "2018"

[dependencies]
primitive-types = { version = "0.9", default-features = false }
evm-core = { version = "0.26", path = "../core", default-features = false }
evm-runtime = { version = "0.26", path = "../runtime", default-features = false }
cyfs-base = { path = "../../../component/cyfs-base" }

[features]
default = ["std"]
std = ["evm-core/std", "evm-runtime/std", "primitive-types/std"]
