[stack.config]
id = "default"
shared_stack = true
shared_stack_stub = false

[[stack.interface]]
type = "http"
listen = "127.0.0.1:1322"

[[stack.interface]]
type = "http-bdt"
vport = "84"

[[stack.interface]]
type = "ws"
enable = true
listen = "127.0.0.1:1323"

[[stack.bdt.endpoint]]
optional = true
host = "$none_local_ip_v4"
port = 8051
protocol = "tcp"
system_default = false

[[stack.bdt.endpoint]]
optional = true
host = "$ip_v6"
port = 8051
protocol = "tcp"
system_default = false

[[stack.bdt.endpoint]]
optional = true
host = "$none_local_ip_v4"
port = 8051
protocol = "udp"

[[stack.bdt.endpoint]]
optional = true
host = "$ip_v6"
port = 8051
protocol = "udp"

# bdt config
[stack.bdt.config]
device = "device"

# TCP port mapping to the WAN address, if there is one
# tcp_port_mapping = 8050

# disable udp transport but sn online via udp only, default is false
# udp_sn_only = false

# sn work mode, "none" will disable sn, default is "normal"
# sn_mode = "normal"

# sn ping interval in seconds, default is 25
# ping_interval = 25